
language: cpp

env:
  global:
    ExternalData_OBJECT_STORES=${HOME}/.ExternalData
    SIMPLEITK_SRC_DIR=${TRAVIS_BUILD_DIR}
    SIMPLEITK_BUILD_DIR=${SIMPLEITK_SRC_DIR}/bld

cache:
  directories:
    - ${ExternalData_OBJECT_STORES}

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required

before_script:
  - sudo apt-get install swig lua5.3 libinsighttoolkit4-dev libgdcm2-dev libvtkgdcm-tools libvtkgdcm-java libfftw3-dev libminc-dev googletest doxygen graphviz
  - cmake --version
  - mkdir -p ${SIMPLEITK_BUILD_DIR}

script:
  - cd ${SIMPLEITK_BUILD_DIR}
  - cmake -DWRAP_LUA:BOOL=OFF -DWRAP_PYTHON:BOOL=OFF -DWRAP_JAVA:BOOL=OFF -DWRAP_CSHARP:BOOL=OFF -DWRAP_TCL:BOOL=OFF -DWRAP_R:BOOL=OFF -DWRAP_RUBY:BOOL=OFF -DBUILD_EXAMPLES:BOOL=OFF -DBUILD_TESTING:BOOL=OFF -DBUILD_DOXYGEN:BOOL=ON -DCMAKE_BUILD_TYPE=Release "${SIMPLEITK_SRC_DIR}"
  - make Documentation
  - tar czf ~/Documentation.tgz Documentation
